version: '3.9'
services:
  db:
    image: mysql:latest
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - .db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/wordpress
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      ENVIRONMENT: Development

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAIL_PORT:-8025}:8025"